POST http://localhost:8000/api/products/
Content-Type: application/json

{
    "name": "very nice product",
    "ingredients": "good ones, other ones",
    "description": "",
    "skin_type": ""

}

###
POST http://localhost:8000/api/accounts/users/
Content-Type: application/json

{
  "username": "testt",
  "password": "string",
  "email": "hello@yahoo.com"
}


###
GET http://localhost:8000/api/accounts/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3MTM2MzAxODl9.BHu8aSn_sEKfQZDiA5Wr6SvO3eBtYLpWG88jIaVlMOA


###
GET http://localhost:8000/api/accounts/profiles/
