POST http://localhost:8000/api/products/
Content-Type: application/json

{
    "name": "very nice product",
    "ingredients": "good ones, other ones",
    "description": "",
    "skin_type": ""

}

###
POST http://localhost:8000/api/accounts/users/
Content-Type: application/json

{
  "username": "test",
  "password": "string",
  "email": "hello@yahoo.com"
}


###
GET http://localhost:8000/api/accounts/jesus/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMywiZXhwIjoxNzEzMTk5Nzg5fQ.HVpr2jwbPlx_M3TbQo1ZT1T9jcBDX5vsJSj7grP36xk