# Generated by Django 5.0.4 on 2024-04-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='skin_type',
            field=models.CharField(choices=[('NORM', 'Normal'), ('DRY', 'Dry'), ('OILY', 'Oily'), ('COMB', 'Combination'), ('SENS', 'Sensitive')], default='NORM', max_length=50, verbose_name='برای پوست ها'),
        ),
    ]
