# Generated by Django 5.0.4 on 2024-04-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skinconcern_customuser_skin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skin_concerns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.skinconcern', verbose_name='skin concerns'),
        ),
    ]
