# Generated by Django 5.0.4 on 2024-04-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ingredients_alter_customuser_skin_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ing_prefer',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_users', to='accounts.ingredient'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ing_sensitive',
            field=models.ManyToManyField(blank=True, related_name='sensitive_to_users', to='accounts.ingredient'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='skin_concerns',
        ),
        migrations.AddField(
            model_name='customuser',
            name='skin_concerns',
            field=models.ManyToManyField(to='accounts.skinconcern', verbose_name='skin concerns'),
        ),
    ]
