# Generated by Django 5.0.4 on 2024-04-12 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_ing_prefer_and_more'),
        ('products', '0011_ingredient_skinconcern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('NORM', 'Normal'), ('DRY', 'Dry'), ('OILY', 'Oily'), ('COMB', 'Combination'), ('SENS', 'Sensitive')], default='NORM', max_length=50, verbose_name='نوع پوست')),
                ('ing_prefer', models.ManyToManyField(blank=True, related_name='preferred_by_users', to='products.ingredient')),
                ('ing_sensitive', models.ManyToManyField(blank=True, related_name='sensitive_to_users', to='products.ingredient')),
                ('skin_concerns', models.ManyToManyField(to='products.skinconcern', verbose_name='skin concerns')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
