# Generated by Django 5.0.4 on 2024-04-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HairProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True)),
                ('hair_type', models.CharField(choices=[('normal', 'Normal'), ('dry', 'Dry'), ('oily', 'Oily'), ('curly', 'Curly'), ('colored', 'Colored')], max_length=20)),
                ('key_ingredients', models.CharField(blank=True, max_length=255)),
                ('benefits', models.CharField(blank=True, max_length=255)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_cruelty_free', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('awards', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
