# Generated by Django 5.0.4 on 2024-04-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairproduct',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
