# Generated by Django 5.0.4 on 2024-04-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_hairproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairproduct',
            name='price',
            field=models.IntegerField(),
        ),
    ]
