# Generated by Django 5.0.4 on 2024-04-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_hairproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairproduct',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='hairproduct',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='hairproduct',
            name='is_cruelty_free',
        ),
        migrations.RemoveField(
            model_name='hairproduct',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='hairproduct',
            name='key_ingredients',
        ),
        migrations.RemoveField(
            model_name='hairproduct',
            name='link',
        ),
        migrations.RemoveField(
            model_name='hairproduct',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='hairproduct',
            name='size',
        ),
        migrations.RemoveField(
            model_name='hairproduct',
            name='volume',
        ),
    ]
