# Generated by Django 5.0.4 on 2024-04-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_hairproduct_awards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='product name')),
                ('description', models.CharField(max_length=150, verbose_name='decription')),
                ('ingredients', models.CharField(max_length=50, verbose_name='list of ingredients')),
            ],
        ),
        migrations.DeleteModel(
            name='HairProduct',
        ),
    ]
