# Generated by Django 5.0.4 on 2024-04-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_delete_hairproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(choices=[('normal', 'نرمال'), ('dry', 'خشک'), ('oily', 'چرب'), ('combination', 'ترکیبی'), ('sensitive', 'حساس'), ('all', 'همه پوست ها')], default='all', max_length=50, verbose_name='برای پوست ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.CharField(max_length=50, verbose_name='مواد تشکیل دهنده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام محصول'),
        ),
    ]
