# Generated by Django 5.0.4 on 2024-04-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='پیش نویس'),
        ),
    ]
